[package]
authors = ["Philipp korber <p.korber@1aim.com>"]
build = "./build.rs"
categories = []
description = "TODO"
keywords = ["mail", "codec", "mime", "smtp"]
license = "MIT OR Apache-2.0"
name = "mail-codec"
readme = "./README.md"
repository = "https://github.com/dathinab/mail-codec"
version = "0.1.0"

[badges]

[badges.travis-ci]
branch = "master"
repository = "dathinab/mail-codec"

[dependencies]
ascii = "0.8.4"
base64 = "0.6.0"
chrono = "0.4.0"
error-chain = "0.10.0"
futures = "0.1.14"
lazy_static = "0.2.8"
mime = "0.3.2"
nom = "3.1.0"
owning_ref = "0.3.3"
quoted_printable = "0.3.0"
rand = "0.3.15"
serde = "1.0.10"
serde_derive = "1.0.10"
